import React from "react";
import Head from "next/head";
import styles from "./about.module.scss";
import Layout from "@/components/Layout";
import Describe from "./components/Describe";
import AboutMe from "./components/AboutMe";
import Experience from "./components/Experience";
import Connect from "./components/Connect";

type Props = {};

export default function AboutPage({}: Props) {
  return (
    <>
      <Head>
        <title>About | Anıl Şenay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <h1 className="text-center">about</h1>
          <h3 className="font-light text-center mt-20 mb-24">
            Hey, welcome to my website!
          </h3>
          <Describe />
          <AboutMe />
          <Experience />
          <Connect />
        </main>
      </Layout>
    </>
  );
}
