import React, { useEffect, useState } from "react";
import Head from "next/head";
import styles from "./home.module.scss";
import Layout from "@/components/Layout";
import CtaLink from "@/components/CtaLink";
import Link from "next/link";
import Projects from "./components/Projects";
import { useTheme } from "next-themes";
import Image from "next/image";
import BlurryBackground from "@/assets/blurry-bg.png";

type Props = {};

export default function HomePage({}: Props) {
  const [mounted, setMounted] = useState(false);
  const { theme, systemTheme } = useTheme();

  useEffect(() => setMounted(true), []);
  if (!mounted) return null;

  const currentTheme = theme === "system" ? systemTheme : theme;

  return (
    <div style={{ position: "relative", overflow: "hidden" }}>
      <Head>
        <title>Anıl Şenay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <div className={styles.titleContainer}>
            <Image
              className={styles.background}
              src={BlurryBackground}
              alt="Blurry Background"
              priority
            />
            <h1>Hey, I am Anıl</h1>
            <h1
              className={`${styles.title} ${
                currentTheme === "dark" ? styles.dark : ""
              }`}
            >
              {"I'm a Software Engineer"}
            </h1>
            <p className={styles.subTitle}>
              Software Engineer{" "}
              <a href="https://cimri.com" target="_blank" rel="noreferrer">
                <b>@Cimri</b>
              </a>
            </p>
          </div>
          <h3>Selected Projects</h3>
          <Projects />
          <CtaLink text="See others" href="/projects" full />

          <h3>About</h3>
          <p className={styles.about}>
            I've been interested in computers and programming since my
            childhood. Coding and design, which I started with curiosity and
            passion, are now a big part of my life. I am interested in{" "}
            <b>JavaScript</b> and <b>Golang</b> mostly.
          </p>
          <CtaLink text="About Me" href="/about" />
          <div
            className={`${styles.connect} ${
              currentTheme === "dark" ? styles.dark : ""
            }`}
          >
            <p>Feel free to reach out to me</p>
            <Link href="/about#connect">Let's Connect</Link>
          </div>
        </main>
      </Layout>
    </div>
  );
}
