import React from "react";
import Head from "next/head";
import styles from "./projects.module.scss";
import Layout from "@/components/Layout";
import TextSlider from "./components/TextSlider";
import Project from "./components/Project";

type Props = {};

export default function ProjectsPage({}: Props) {
  return (
    <>
      <Head>
        <title>Projects | Anıl Şenay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <h1 className="text-center">projects</h1>
          <h3 className="font-light text-center mt-20 mb-24">
            Some of my personal projects in{" "}
            <b className="font-medium">Github</b>
          </h3>
          <TextSlider />
          <div className={styles.projects}>
            <Project />
            <Project />
            <Project />
            <Project />
          </div>
        </main>
      </Layout>
    </>
  );
}
